### ISSUE TITLE
How to get data from WP to the theme

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/component-themes#1]
This is a challenging question. PHP-based themes have no need to consider the issue because they are entirely server-side rendered and so each part of the theme (or even components) can directly request the data they need from the database.

Here we need two ways to access the data: in the PHP components on the server as well as in the JS components on the client.

If the data has already been rendered by the PHP, it should be passed down to the JS, which simplifies the issue most of the time. In some cases, however, a JS component might render without the PHP component having been rendered first. Examples include: components which are too complex to have a PHP version and components rendered as a preview inside an editor.

To that end it would be nice if there was a standard way for each component to specify which data it needs and for the rendering engines to be able to request that data.

As a first draft I've added a property, `requiredApiData`, to each component. If set, the property specifies REST API endpoints which have the data the component needs. The data is then passed as a prop to the component when it is ready. You can read [my very rough documentation here](https://github.com/Automattic/component-themes/blob/master/src/themes/components/README.md#required-data). 

I used REST API endpoints because I presume we'll have to use the REST API to get server data when using the JS rendering engine. That of course needs a lot of thought around authentication and may be a lot of work.

On the server side, sadly I don't think it's possible to request API endpoints, which means we have to get the data some other way. This makes things more complicated. I tentatively solved this by having a function that parses the requested endpoint and re-creates the API response using standard WP functions. It then uses that data for PHP rendering and bootstraps that data directly to the JS rendering engine.

I don't love this technique and it is probably not sustainable, but it was a first attempt. Other suggestions are very welcome!

One idea which has been used in similar efforts is the [QueryComponent of Calypso](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#query-components). We could adopt that approach.

My goal is to try to keep the amount of work for component developers at a minimum.

**Comment by sirbrillig** [comment]
> On the server side, sadly I don't think it's possible to request API endpoints,

@kwight pointed out that this should actually be possible. I was thinking of something else.

**Comment by sirbrillig** [comment]
Even if we use the REST API on the server-side, however, that means that every page request will take quite a lot longer because it has to make several API requests (and load WP each time) before it can complete. That's not ideal.

**Comment by westonruter** [comment]
@sirbrillig WordPress can efficiently perform multiple internal REST API requests in a single instance without the overhead of opening HTTP connections, and in that regard it shouldn't be any different than making a bunch of `WP_Query` instances. Example:

```php
$server = rest_get_server();
$request = new WP_REST_Request( 'GET', '/wp/v2/posts' );
$response = $server->dispatch( $request )
```

**Comment by sirbrillig** [comment]
😯 wow! That's good to know! This is what I get for never trying to use the REST API from within WP before. That may make this issue a lot easier, since both server and client could request endpoint data directly.

**Comment by sirbrillig** [comment]
Updated to use `WP_REST_Request` in 5f0b89910f1eb8da972fde5d6ff86b320987c171. Seems to work well! 👍

**Comment by sirbrillig** [comment]
I came up with an alternative version of the `requiredApiData` technique which is more Redux-like in #3
