### ISSUE TITLE
build/app.js and build/core-components.js are not loaded

### ISSUE THREAD

**Issue by vladanost** [Automattic/component-themes#12]
In class-component-themes-public.php these files are hardcoded and are not loaded when installed as plugin on regular WP installation.

It works when they are written like this:
```php
<script src="<?php echo plugin_dir_url( __FILE__ ); ?>../build/app.js"></script>
<script src="<?php echo plugin_dir_url( __FILE__ ); ?>../build/core-components.js"></script>
```

I can do a pull request but not sure what is the intention here in the first place with hardcoding.

**Comment by sirbrillig** [comment]
Should be fixed by #14
