### ISSUE TITLE
Downgrade PHP features to 5.2

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/component-themes#5]
We're trying to make this plugin work with the minimum required PHP version of core WordPress, which is 5.2.4. 

That means we'll need to replace the array shorthand syntax (`[1, 2, 3]`) with the old syntax (`array(1, 2, 3)`).

It also means we'll need to remove all anonymous functions (this might be tricky).

We will also need to make sure that all dynamic static property references are done with array syntax.

There may be additional things.

**Comment by taggon** [comment]
I just added Travis CI build status to README to help support old PHP versions. :)
https://github.com/Automattic/component-themes/commit/720ae09087638307b44b5439254d800a8565796c

**Comment by taggon** [comment]
Almost done. :)

**Comment by taggon** [comment]
Merged! 🎉
